### ISSUE TITLE
Sporadically Redirected to WP Login

### ISSUE THREAD

**Issue by phend2wj** [MrApplejuice/wp-autologin-links#6] opened 2019-01-18 13:55 UTC
Hi,

We're using v.1.09 and have a autologin link that we've generated for a specific user. This link is used in our application to access the WP site, without having to login. It's works most of the time, but sporadically our users are redirected to the WP login page. The solution we've found is to login to WP and logout the user with the autologin link, then log back into WP as that user. Any thoughts as to why this would happen?

Thanks!

**Comment by MrApplejuice** [comment] 2019-02-11 22:34
Hi there! I just released version 1.10.0. Can you update and check if this problem still occurs? I cannot reproduce the bug and just assume that this is a caching issue. I am not sure though.

Also: This is an duplicate of #3

**Comment by phend2wj** [comment] 2019-02-11 23:54
I've updated to 1.10.0. We'll keep an eye on it and let you know if it happens again. Thanks!

**Comment by phend2wj** [comment] 2019-02-14 17:00
It had been working great, but unfortunately I was just routed back to the WordPress login screen. Any other ideas on what might be causing this? Any setting in WordPress you think should be changed?

**Comment by MrApplejuice** [comment] 2019-02-18 16:45
I will have a look again. Until I find a way to reproduce this issue I feel that I am treading water though. Therefore, I cannot promise a quick fix. I'll keep you in the loop!

**Comment by MrApplejuice** [comment] 2019-10-20 21:42
I did not see any recurring instances of this problem with the newest version of the plugin. I assume that it is fixed and that  everything works now. Finally! :smile:

**Closed by MrApplejuice** 2019-10-20 21:42 UTC
Labels: bug
