### ISSUE TITLE
Not Working on chrome

### ISSUE THREAD

**Issue by horaceleung** [MrApplejuice/wp-autologin-links#3] opened 2018-12-03 09:40 UTC
This plugin does not work properly on chrome browsers. You have to refresh the page twice for it to work. Can you please advice if this can be fixed?

**Comment by MrApplejuice** [comment] 2018-12-05 00:06
Well, I just tested it and it just works fine here. I need more info to do anything with this bug report. If you provide more info I might be able to fix something but as it stands I cannot find any bug.

If you provide extra info within the next week, I can have a look, otherwise I will close the ticket.

**Comment by MrApplejuice** [comment] 2019-01-04 12:01
# Extracted from reports to date

- Happens on
  - Chrome on Mac (cannot test this because I do not have a Mac)
- Not observable on
  - Firefox on Linux
  - Chromium on Linux

# Hypotheses

- Bug in Chrome on Mac since I cannot observe it and do not get many reports about this issue.
- Caching seems to be an issue: chrome "loads the page very quickly" so maybe it caches the get-based autologin-link.

# Solution

If this is caused by caching, a solution might be to include Cache-Control headers in the redirect response (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) to prevent chrome from caching any autologin-link responses.

**Comment by MrApplejuice** [comment] 2019-01-18 01:01
I will release the fix-attempt in v1.10. I do not know if this will fix the issue at hand. I will close this issue in the mean time, so if it did not fix the issue, please reopen this.

**Closed by MrApplejuice** 2019-01-18 01:01 UTC
Labels: unconfirmed
